# Generated by Django 2.2.4 on 2019-08-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Dawkowanie')),
                ('time_interval', models.IntegerField(verbose_name='Co ile dni')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Imię')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Jednostka')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('pets', models.ManyToManyField(null=True, through='pets.Dosage', to='pets.Pet', verbose_name='Zwierzę')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='dosage',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pet', verbose_name='Zwierzę'),
        ),
        migrations.AddField(
            model_name='dosage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Product', verbose_name='Nazwa'),
        ),
    ]
