# Generated by Django 2.2.4 on 2019-08-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_dosage_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosage',
            old_name='time_interval',
            new_name='interval',
        ),
    ]
