# Generated by Django 2.2.4 on 2019-08-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20190805_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ilość'),
        ),
    ]
