# Generated by Django 2.2.4 on 2019-08-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20190805_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosage',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='date_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.Unit', verbose_name='jednostka'),
        ),
    ]
