# Generated by Django 2.2.4 on 2019-08-18 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20190818_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Od kiedy'),
        ),
    ]
