# Generated by Django 2.2.4 on 2019-08-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_auto_20190818_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Uwagi'),
        ),
    ]
