branch-defaults:
  aws-eb:
    environment: django-env
    group_suffix: null
  develop:
    environment: django-env
global:
  application_name: pet_tracker
  branch: null
  default_ec2_keyname: UdemyCourseKeyPair
  default_platform: Python 3.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
